### ISSUE TITLE
Hunter of Glacial Forest Mixup

### ISSUE THREAD

**Issue by applephrans** [kel-z/HSR-Scanner#11]
I noticed that consistently hand and body pieces for Hunter of Glacial Forest get mixed up. I have to manually check and fix

**Comment by kel-z** [comment]
Looks like the slotKey for body and feet were switched around. I didn't see anything wrong with hand though -- did you mean feet and body were getting mixed up?

**Comment by applephrans** [comment]
Yeah thats what I meant. Sorry

**Comment by kel-z** [comment]
No worries! Lmk if [v0.2.2](https://github.com/kel-z/HSR-Scanner/releases/tag/v0.2.2) fixes this issue

**Comment by applephrans** [comment]
Just tested it. Everything seems to match up correctly!
