### ISSUE TITLE
Sync names with KQM-SRL

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#17]
Hey!

V0.2.3 seems scan chars okay.

Any chances to adopt GOOD format from Genshin Impact? HSR-Scanner pretty near already - some minor tweaks and it would looks GOOD.

Say, GOOD uses CamelCase names like
  "artifacts": [
    {
      "setKey": "GildedDreams",
      "slotKey": "flower",
      "level": 20,
      "rarity": 5,
      "mainStatKey": "hp",
      "location": "Collei",
      "lock": false,
      "substats": [
        {
          "key": "critDMG_",
          "value": 13.2
        },
        {
          "key": "eleMas",
          "value": 42.0
        },
        {
          "key": "enerRech_",
          "value": 11.7
        },
        {
          "key": "critRate_",
          "value": 7.4
        }
      ]
    },

Also it uses another name convention for keys - `critDMG_` instead of `CRIT DMG_`. Etc.

I tried to find formal specs for GOOD but failed. But I can supply some scanner outputs in GOOD format if you interested.

May be some option to export in GOOD format?

Also if you interested - here some data from HSR which can be used to sync with new characters: https://github.com/KQM-git/SRL/tree/master/src/data

**Comment by kel-z** [comment]
Formal documentation for `GOOD` can be found [https://frzyc.github.io/genshin-optimizer/#/doc](here).

I was planning on waiting for any star rail optimizer to come out first so I can change the current key naming conventions accordingly. Maybe I can add a custom output config tab. 

Also yes, ideally in the future I'd update the scanner by pulling the data from a repo (such as KQM) so I don't need to keep releasing new versions every time a star rail update happens.

**Comment by supernova-ws** [comment]
Thank you for link! How I can miss it?..
