### ISSUE TITLE
Asta and Tingyun talent scan failed

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#18]
v.0.2.3 beta

```
Asta: Failed to parse 'talent' level. Setting to 1.
Tingyun: Failed to parse 'talent' level. Setting to 1.
```
Screenshots
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/b95a3410-15eb-47c4-b898-72a928e3cd15)
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/fd0bcd16-95d1-414b-a2ee-97533e19768e)

**Comment by kel-z** [comment]
#21 Scanner now uses OCR model for `DIN Alternate Bold` font. Hopefully now it will scan talent levels at least 100% correctly.
