### ISSUE TITLE
Suggestion: Scan character speed up

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#20]
Hey!

I notices that slowest character scan moment is an eidolons scan due to delay of game itself. Unfortunately, eidolon screens opens twice during scan of one character: fitst time when you switching from prev character then when switching to scan eidolons (applies for 2nd character and beyond).

I offer to star scanning character from eidolons and finish  scanning character on "Details" page then switch character to next one - i.e reversing current scan order to "Eidolons"->"Relics"->"Traces"->"Light Cone"->"Details".

**Comment by kel-z** [comment]
Good suggestion. The eidolon screen does open twice during the scan. If I find a way to cleanly reverse the order of the character scanning without creating clutter to the code, I will definitely consider optimizing this in the future.

**Comment by supernova-ws** [comment]
Mate! Nice to see you back and even pushed new release! Started to worry a bit 'cause of your long absence. Hope you fine and well.

**Comment by kel-z** [comment]
Thanks! Yeah, the scanner was updated for both 1.3 and 1.4 back then, so I was waiting for the release of 1.5 to come closer before updating it again.

**Comment by supernova-ws** [comment]
Nice to know you well and kicking! Your work is very appreciated and your tool is irreplaceable (figural). I think you should post link to your perfect scanner to thematical forums - like reddit branch and/or hoyoverse's forums.

About scan speed up: I believe there is simple solution for now - just switch to "Details" pan before switching character.

**Comment by supernova-ws** [comment]
Much faster in 0.5.1b
