### ISSUE TITLE
Broken main stat field 

### ISSUE THREAD

**Issue by TimohaIsGod** [kel-z/HSR-Scanner#22]
[HSRScanData_20231105_092732.json](https://github.com/kel-z/HSR-Scanner/files/13266281/HSRScanData_20231105_092732.json)
broken main stat field on 0.3 version. It's always "HP" or ""

**Comment by kel-z** [comment]
Interesting. What game resolution? Fullscreen/windowed? Does this still happen when you scan in a different/darker location?

**Comment by kel-z** [comment]
Looks like it's 1280x720 that's causing this to happen. I'll do some more digging.

**Comment by kel-z** [comment]
Heyo, see if this fixed it [v0.3.1](https://github.com/kel-z/HSR-Scanner/releases/tag/v0.3.1).

**Comment by TimohaIsGod** [comment]
thanks!
