### ISSUE TITLE
feature request | language support

### ISSUE THREAD

**Issue by jackeywcy** [kel-z/HSR-Scanner#24]
Hi  Kel-z,
  May you add support for star rail version of chinese and other versions. Particularly in the game name detection module. In current version the game with chinese name "崩坏：星穹铁道" could not be captured by the game. We would be able to switch language resources in game to English, so no need for further adjustments. Many thanks if you'd like to reply.

**Comment by kel-z** [comment]
Helloo, does the game name not change to "Honkai: Star Rail" when you switch the text to English?

**Comment by jackeywcy** [comment]
Hello, as I am running this application in Chinese server, the application still run in "崩坏：星穹铁道". If there is any concern please tell me.

**Comment by kel-z** [comment]
I see. I can make the scanner detect the game name "崩坏：星穹铁道", but it will only scan English still.

**Comment by kel-z** [comment]
See if this works [v0.3.2](https://github.com/kel-z/HSR-Scanner/releases/tag/v0.3.2).

**Comment by Sevih** [comment]
Fun fact: The name when running the game in English is "Honkai: Star Rail," but when you switch the game language to French, it becomes "Honkai : Star Rail." This space between Honkai and the colon seems to be causing the scanner to fail to detect the game.

**Comment by kel-z** [comment]
implemented
