### ISSUE TITLE
Substat parsing failed [v0.3.0]

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#27]
[23:25:38] > Relic ID 389: Failed to get value for sub-stat: DEF. Error parsing sub-stat value: V3.
[23:25:51] > Relic ID 460: Failed to get value for sub-stat: ATK. Error parsing sub-stat value: V3.

        {
            "set": "Knight of Purity Palace",
            "slot": "Hands",
            "rarity": 4,
            "level": 9,
            "mainstat": "ATK",
            "substats": [],
            "location": "Gepard",
            "lock": true,
            "_id": "relic_389"
        },
![__gepard_hands](https://github.com/kel-z/HSR-Scanner/assets/412702/d1bbb204-6d4c-4345-8278-3c3d8260ca18)

        {
            "set": "Inert Salsotto",
            "slot": "Planar Sphere",
            "rarity": 3,
            "level": 0,
            "mainstat": "ATK",
            "substats": [
                {
                    "key": "CRIT DMG_",
                    "value": 3.8
                }
            ],
            "location": "",
            "lock": true,
            "_id": "relic_460"
        },

![_inert_salsoto_460](https://github.com/kel-z/HSR-Scanner/assets/412702/daca5c34-85b3-4190-af01-8ae6f197c880)
I believe this is right one

**Comment by supernova-ws** [comment]
Looks like not happens in v0.3.1 on short scan... Let me recheck

**Comment by supernova-ws** [comment]
WHOA! New version 0.3.1 nailed it all! No more errors on scanning!

Moreover - this OCR tuning made thing a blast! Rough estimation - x1.5+ speedup (not measured, TBH)! That's really a breeze!

Thanks, mate! It really helps.

(you can close this issue)

**Comment by kel-z** [comment]
Haha np!
