### ISSUE TITLE
Light Cone and Relic scanner always returns quantity parsing error

### ISSUE THREAD

**Issue by frenzy85** [kel-z/HSR-Scanner#3]
Error:
"Failed to parse quantity. Did you start the scan from the ESC menu?"
Program accurately goes to Light Cone or Relic screen based on scan settings, but stops there and returns the above error message.

Troubleshooting:
Tried Windowed and Fullscreen at 1920x1080 and 1600x900
Tried all the preset graphic settings
Found the darkest area I could find (a corner in Storage Zone, HSS)

**Comment by kel-z** [comment]
Looks like the screenshotting module doesn't play nicely with multiple monitors. Do you have multiple monitors? If so, try again but with star rail on your primary monitor.

**Comment by frenzy85** [comment]
That did it.
Thanks a bunch, mate.
