### ISSUE TITLE
[critical] Scan aborted on artifact - HSR v1.5, scanner v0.3.1

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#30]
Log:
[00:01:58] > Finished scanning characters
[00:02:15] > Scan aborted with error: 'NoneType' object has no attribute 'read'

![image](https://github.com/kel-z/HSR-Scanner/assets/412702/b86c58e0-1069-4af7-bda9-3e84327f2ab3)

I presume - this is culprit - relic #32:
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/e1287e46-51b5-4243-af77-819a2886c184)

Just for a caution - relic #33:
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/e01c6cfe-1628-43cd-bd8a-351d8c05cd6d)

And relic #31
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/78f597cb-b205-4c03-886d-d8856e638313)

**Comment by supernova-ws** [comment]
Ugh... I presume - it's due to too light background? I'll rescan with other bg

**Comment by kel-z** [comment]
Interesting. What resolution did you scan with? Did it happen again?

**Comment by supernova-ws** [comment]
1920x1080 - as on image. Or GitHub scaled it down?

After I changed location and background under relic's details became almost black I rescanned all again and this time HSR Scanner OCRed everything right.

**Comment by kel-z** [comment]
I see. I'll look into where that error comes from, since it's not immediately obvious right now. Closing for now.
