### ISSUE TITLE
[bug] 0.5.1-pre1 Relics on Welt incorrectly recognized as male Trailblazers ones.

### ISSUE THREAD

**Issue by Giftofdawn** [kel-z/HSR-Scanner#43]
My guess is scanner is looking for female Trailblazers portrait on relics to determine its location, so it matches with Welt instead because he looks similar to male Trailblazer. There was similar problem with Silver Wolf and Lynx in previous versions of the scanner, but now it seems to be fixed.

![image](https://github.com/kel-z/HSR-Scanner/assets/48837903/ddd59a3d-c233-4b11-8162-4aabf358f30a)

Amount of relics placed on Trailblazer:
![image](https://github.com/kel-z/HSR-Scanner/assets/48837903/f7407794-2748-4b13-92b0-83366ce9b97c)

**Comment by kel-z** [comment]
What window resolution does this happen on?

**Comment by Giftofdawn** [comment]
> What window resolution does this happen on?

1920х1080 windowed mode
![image](https://github.com/kel-z/HSR-Scanner/assets/48837903/36da1806-0140-4cb8-a984-684b0a99afde)

**Comment by kel-z** [comment]
See if latest release fixes this issue (I don't have Welt to test).

**Comment by Giftofdawn** [comment]
Yea, it is fixed now
