### ISSUE TITLE
[bug] 0.5.1b Relic ID XX: Failed to get value for substat: HP.

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#46]
Started new character to investigate some early-game details. When scanning relics some errors in logs:
[21:55:52] > Relic ID 73: Failed to get value for substat: HP.
        {
            "set": "Fleet of the Ageless",
            "slot": "Planar Sphere",
            "rarity": 2,
            "level": 0,
            "mainstat": "Ice DMG Boost",
            "substats": [],
            "location": "March 7th",
            "lock": false,
            "_id": "relic_73"
        },
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/88265923-5666-4b71-9596-65f52856ca7a)

[21:55:52] > Relic ID 75: Failed to get value for substat: HP.
        {
            "set": "Fleet of the Ageless",
            "slot": "Link Rope",
            "rarity": 2,
            "level": 0,
            "mainstat": "Break Effect",
            "substats": [],
            "location": "",
            "lock": false,
            "_id": "relic_75"
        },
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/32c440f9-3ba0-4e96-8e56-75d60b64cd8d)

**Comment by kel-z** [comment]
It probs reads "Fleet" then it autocorrects to "HP" as the closest match. Needs more looking into, though not highest priority rn.

**Comment by supernova-ws** [comment]
Looks like it was fixed in 0.6.0b. Unfortunately - other problem arise https://github.com/kel-z/HSR-Scanner/issues/58
