### ISSUE TITLE
Too few relics scanned

### ISSUE THREAD

**Issue by mveselov-de** [kel-z/HSR-Scanner#53]
I have around 1300 relics in total. For some reason scanner is only showing 431 in output file. Scan wasn't interrupted, windowed 1920x1080 resolution, looking at the floor of parlor car.

**Comment by kel-z** [comment]
Was the minimum relic level filter set to 0? What resolution, and was it in window mode or was it fullscreen?

**Comment by kel-z** [comment]
Also wondering if it missed a leading 1 when grabbing the relic total, did u have 1431 relics exactly in your inventory or something like that? Did it happen again when rescanning?

**Comment by mveselov-de** [comment]
Omg, I feel so stupid now. Of course it was a min relic level. Maybe you can change the default to 0 ?

**Comment by kel-z** [comment]
Lol no worries, at this point I think the default should be 0 too. I'll update that in the next release.

**Comment by kel-z** [comment]
implemented
