### ISSUE TITLE
Scan aborted with error ValueError: Failed to parse quantity.

### ISSUE THREAD

**Issue by ShamankaS** [kel-z/HSR-Scanner#56]
I tried to start scan, but character always used basic attack and after that scanner stopped with error `[01:46:26] > Scan aborted with error ValueError: Failed to parse quantity. Did you start the scan from the ESC menu?. Try scanning with a different in-game background.` Every try scanner didn't open any game menu (bag or characters). Tried to change location, to stand in dart corners, but always have same error. 
I ran scanner several times in a row with different options and for about 10-15 starts program worked normally 1-2 times.

Full error log: 
[01:46:20] > Starting scan...
[01:46:20] > Scanning relics...
[01:46:26] > Scan aborted with error ValueError: Failed to parse quantity. Did you start the scan from the ESC menu?. Try scanning with a different in-game background.

Game settings: 
![image](https://github.com/kel-z/HSR-Scanner/assets/115077020/2f138493-249b-4d23-bc14-d8eaa3ee2f6b)
Scan options:
![image](https://github.com/kel-z/HSR-Scanner/assets/115077020/d52e7b50-13c7-471f-8014-e8201c150776)

**Comment by kel-z** [comment]
Did you change your inventory key shortcut? (i.e. does pressing 'b' open the inventory)

**Comment by ShamankaS** [comment]
> Did you change your inventory key shortcut? (i.e. does pressing 'b' open the inventory)

Nah, I use all standard shortcuts

**Comment by kel-z** [comment]
Hmm, the scanner can sometimes be doing its inputs too fast depending on the computer. For the basic attack thing to happen, does it take longer than 1 second for the menu to close when you press ESC?

I'm working on adding a customizable delay soon, so users with slower computers can add a longer delay to prevent the inventory key from being pressed too fast. That should hopefully fix this problem.

**Comment by ShamankaS** [comment]
```
[01:46:20] > Starting scan...
[01:46:20] > Scanning relics...
[01:46:26] > Scan aborted with error ValueError: Failed to parse quantity. Did you start the scan from the ESC menu?. Try scanning with a different in-game background.
```
After "Scanning relics" scanner close esc-menu, wait something, character use basic attack and then last error down in log and scanner stopped

**Comment by ShamankaS** [comment]
strange bug, because I got it after several attempts to start the scanner and now I can't reproduce bug because the scanner constantly starts without problems >_<

**Comment by kel-z** [comment]
Yeah I suspect it is because the scanner presses the inventory shortcut too fast before your game fully closes the ESC menu. I'll add something soon to address that (like a short delay that users can customize for the scanner speed?)

**Comment by ShamankaS** [comment]
I tested new release and it didn't solve my problem. I set Navigation speed to +5000 ms - this also did not solve the problem. Scanner doesn't open inventory or characters.

**Comment by kel-z** [comment]
Is the app being run as administrator?

**Comment by kel-z** [comment]
Nvm it should be since it's pressing ESC. Hmm...

**Comment by kel-z** [comment]
Do you have multiple monitors? Maybe switching which monitor the game is on will change something?

**Comment by ShamankaS** [comment]
I have two monitors.
But I have already tried scanning several times: I put the character on train in a dark corner and then scanner works without errors and without my bug

**Comment by ShamankaS** [comment]
I think I can close this request because bug has been fixed
