### ISSUE TITLE
premature termination of the scan

### ISSUE THREAD

**Issue by TimohaIsGod** [kel-z/HSR-Scanner#6]
premature termination of the scan when setting the minimum level = 6(on 25 relic always)
but i have more than 25 items
![image](https://github.com/kel-z/HSR-Scanner/assets/18659544/1b00fc35-31fc-4ee6-abba-bab34509314b)

**Comment by TimohaIsGod** [comment]
full scaning works fine(with minimum level = 0)

**Comment by kel-z** [comment]
the current model being used for tesseract sucks and is reporting the relic levels wrong... gonna need to train a new model specifically for star rail soon.

as a bandaid fix in the meantime, I added preprocessing for relic level images which would make the whole OCR part take longer, but hopefully it will work correctly now... lmk
