### ISSUE TITLE
[feature request] Do OCR to the achievements and export in UIAF standard

### ISSUE THREAD

**Issue by RosieDu21** [kel-z/HSR-Scanner#60]
Hi, I noticed this repo which is so great. Actually, I'm looking for an OCR tool to export the hsr achievements, and it seems yours is the most close one. Can you expand the function of this tool to allow it to export the achievements? That will be useful!

If you're willing to do this, I'd like to recomment the UIAF standard. It's an open source standard for json file which records the achivements of Genshin and HSR. The author group have also made some other standards for other things like the gacha history, and they have cooperated with lots of tools, so I think they're reliable. Anyway, this is just a recommendation. If you trust them, you can try, if not, please just ignore my words, that's ok.

Thanks in advance!

**Comment by kel-z** [comment]
Sounds interesting. If I have time I can start looking into it.

**Comment by BastianBN** [comment]
I was thinking about working on this kind of feature too in the next days, do you need help for it ? I'm really hyped for an achievement parser

**Comment by kel-z** [comment]
I haven't tested out ways of navigating the achievements yet (nor thought of how I would implement it). There does exist [this one](https://github.com/hashblen/HSRAchievementScannerPOC) though, but I haven't tried it personally.

**Comment by kel-z** [comment]
Looks like there is this now: https://github.com/hashblen/HSRAchievementScanner

This is not the exact same format, but you can probably convert the output into the format you want.
