### ISSUE TITLE
Hotkeys are too limited

### ISSUE THREAD

**Issue by SleepingPanda** [kel-z/HSR-Scanner#67]
Right now it seems the hotkeys are limited to letters and numbers but I've remapped my game hotkeys to the F-row of keys. I'd like to be able to likewise assign these in HSR-Scanner.

**Comment by kel-z** [comment]
Ah I didn't know it was possible to assign shortcuts to F keys. I'll get it sorted out, thanks!

**Comment by kel-z** [comment]
implemented, reopen if there are some keys that I missed
