### ISSUE TITLE
Scanning doesn't work with different keyboard layouts.

### ISSUE THREAD

**Issue by DexlerXD** [kel-z/HSR-Scanner#70]
I've encountered an issue, where standard binds in configure menu doesn't seem to work properly

I have a cyrillic layout in my windows, and I tried to scan my account with standard configuration of the scanner. It didn't work at first. Only after I changed layout to english or changed the configuration to a cyrillic characters it started working. It was pretty annoying at first, but I managed to fix it, hope it'll be patched foe everyone.

**Comment by kel-z** [comment]
I think I need more information since I only have a standard English keyboard. What are the steps for me to replicate this bug on my computer?

**Comment by DexlerXD** [comment]
> I think I need more information since I only have a standard English keyboard. What are the steps for me to replicate this bug on my computer?

1. Have more than 1 keyboard layouts in your windows;
2. Launch scanner and don't change any binds settings in configuration;
3. Try to start the scan with different from English layout;

In my case, scan just didn't work after it left the phone menu. I had to either change my layout to English or change bindings on config to the currently used layout. Hope that helps!

**Comment by kel-z** [comment]
Thank you, that does help a lot. Looks like the Python library I use for automated keyboard input behaves strangely when the computer has a layout set to anything other than English ([ref](https://github.com/moses-palmer/pynput/issues/187)), so I'll have to see if there's an easy workaround for that. For now, it might be good enough that the scanner works after changing the binding in the configure tab.
